export const ALL_MATRIX = "ALL_MATRIX";
export const ALL_MATRIX_FAILURE = "ALL_MATRIX_FAILURE";
export const INITIAL_MATRIX = "INITIAL_MATRIX";
export const RESET = "RESET";
export const SET_COLOR = "SET_COLOR";
export const PIXEL_COLOR_UPDATE = "PIXEL_COLOR_UPDATE";
export const UPDATE_PIXEL_COLOR = "UPDATE_PIXEL_COLOR";
